{application,money,
             [{applications,[kernel,stdlib,elixir]},
              {description,"Elixir library for working with Money safer, easier, and fun, is an interpretation of the Fowler's Money pattern in fun.prog.\n"},
              {modules,['Elixir.Money','Elixir.Money.Currency',
                        'Elixir.Money.Currency.Ecto.Type',
                        'Elixir.Money.Ecto.Amount.Type',
                        'Elixir.Money.Ecto.Composite.Type',
                        'Elixir.Money.Ecto.Currency.Type',
                        'Elixir.Money.Ecto.Map.Type',
                        'Elixir.Money.Ecto.NumericCurrency.Type',
                        'Elixir.Money.Ecto.Type','Elixir.Money.Sigils',
                        'Elixir.Phoenix.HTML.Safe.Money',
                        'Elixir.String.Chars.Money']},
              {registered,[]},
              {vsn,"1.7.0"}]}.
