defmodule ChainBusinessManagement.Repo.Migrations.AddBankCatalogsRegisters do
  use Ecto.Migration

  def up do
    execute "
      INSERT INTO banks_catalog
      (code, enabled, name, logo, inserted_at, updated_at)
      VALUES
      ('002',true,'Citibanamex','Citibanamex',now(),now()),
      ('006',true,'Bancomext','Banco Nacional de Comercio Exterior',now(),now()),
      ('009',true,'Banobras','Banco Nacional de Obras y Servicios Públicos',now(),now()),
      ('012',true,'BBVA','BBVA',now(), now()),
      ('014',true,'Santander','Banco Santander',now(),now()),
      ('019',true,'Banjercito','Banco Nacional del Ejército, Fuerza Aérea y Armada',now(),now()),
      ('021',true,'HSBC','HSBC México',now(),now()),
      ('030',true,'Banco del Bajío','Banco del Bajío',now(),now()),
      ('032',true,'IXE','IXE Banco',now(),now()),
      ('036',true,'Inbursa','Banco Inbursa',now(),now()),
      ('037',true,'Interacciones','Banco Interacciones',now(),now()),
      ('042',true,'Mifel','Banca Mifel',now(),now()),
      ('044',true,'Scotiabank','Scotiabank Inverlat',now(),now()),
      ('058',true,'Banregio','Banco Regional de Monterrey',now(),now()),
      ('059',true,'Invex','Banco Invex',now(),now()),
      ('060',true,'Bansi','Bansi',now(),now()),
      ('062',true,'Afirme','Banca Afirme',now(),now()),
      ('072',true,'Banorte','Banco Mercantil del Norte',now(),now()),
      ('102',true,'The Royal Bank','The Royal Bank of Scotland México',now(),now()),
      ('103',true,'American Express','American Express Bank',now(),now()),
      ('106',true,'Bansa','Bank of America México',now(),now()),
      ('108',true,'Tokyo','Bank of Tokyo - Mitsubishi UFJ',now(),now()),
      ('110',true,'JP Morgan','Banco J.P.Morgan',now(),now()),
      ('112',true,'Monex','Banco Monex',now(),now()),
      ('113',true,'Ve por más','Banco Ve Por Mas',now(),now()),
      ('116',true,'ING','ING Bank',now(),now()),
      ('124',true,'Deutsche','Deutsche Bank México',now(),now()),
      ('126',true,'Credit Suisse','Banco Credit Suisse',now(),now()),
      ('127',true,'Azteca','Banco Azteca',now(),now()),
      ('128',true,'Autofin','Banco Autofin México',now(),now()),
      ('129',true,'Barclays','Barclays Bank México',now(),now()),
      ('130',true,'Compartamos','Banco Compartamos',now(),now()),
      ('131',true,'Famsa','Banco Ahorro Famsa',now(),now()),
      ('132',true,'Multiva','Banco Multiva',now(),now()),
      ('133',true,'Actinver','Banco Actinver',now(),now()),
      ('134',true,'Walmart','Banco Wal-Mart de México Adelante',now(),now()),
      ('135',true,'Nafin','Nacional Financiera',now(),now()),
      ('136',true,'Interbanco','Inter Banco',now(),now()),
      ('137',true,'Bancoppel','BanCoppel',now(),now()),
      ('138',true,'ABC Capital','ABC Capital',now(),now()),
      ('139',true,'UBS','UBS Bank México',now(),now()),
      ('140',true,'Consubanco','Consubanco',now(),now()),
      ('141',true,'Volkswagen','Volkswagen Bank',now(),now()),
      ('143',true,'CI Banco','CIBanco',now(),now()),
      ('145',true,'Base','Banco Base',now(),now()),
      ('166',true,'Bansefi','Banco del Ahorro Nacional y Servicios Financieros',now(),now()),
      ('168',true,'Hipotecaria Federal','Sociedad Hipotecaria Federal',now(),now()),
      ('600',true,'Monex','Monex Casa de Bolsa',now(),now()),
      ('601',true,'GBM','GBM Grupo Bursátil Mexicano',now(),now()),
      ('602',true,'Masari','Masari Casa de Bolsa',now(),now()),
      ('605',true,'Value','Value',now(),now()),
      ('606',true,'Estructuradores','Estructuradores del Mercado de Valores Casa de Bolsa',now(),now()),
      ('607',true,'Tiber','Casa de Cambio Tiber',now(),now()),
      ('608',true,'Vector','Vector Casa de Bolsa',now(),now()),
      ('610',true,'B&B','B y B', now(), now()),
      ('614',true,'Accival','Acciones y Valores Banamex',now(),now()),
      ('615',true,'Merrill Lynch','Merrill Lynch México',now(),now()),
      ('616',true,'Finamex','Casa de Bolsa Finamex',now(),now()),
      ('617',true,'Valmex','Valores Mexicanos Casa de Bolsa',now(),now()),
      ('618',true,'Unica','Unica Casa de Cambio',now(),now()),
      ('619',true,'Mapfre','MAPFRE Tepeyac',now(),now()),
      ('620',true,'Profuturo','Profuturo GNP',now(),now()),
      ('621',true,'Actinver Casa de Bolsa','Actinver Casa de Bolsa',now(),now()),
      ('622',true,'Operadora Actinver','OPERADORA ACTINVER',now(),now()),
      ('623',true,'Skandia','Skandia Vida',now(),now()),
      ('626',true,'Deutsche Securities','Deutsche Securities',now(),now()),
      ('627',true,'Zurich','Zurich Compañía de Seguros',now(),now()),
      ('628',true,'Zurich Vida','Zurich Vida',now(),now()),
      ('629',true,'Su casita','Hipotecaria Su Casita',now(),now()),
      ('630',true,'Intercam','Intercam Casa de Bolsa',now(),now()),
      ('631',true,'CI Cada de Bolsa','Casa de Bolsa',now(),now()),
      ('632',true,'Bulltick','Bulltick Casa de Bolsa',now(),now()),
      ('633',true,'Sterling','Sterling Casa de Cambio',now(),now()),
      ('634',true,'Fincomun','Fincomún',now(),now()),
      ('636',true,'HDI Seguros','HDI Seguros',now(),now()),
      ('637',true,'Order Express','Order Express Casa de Cambio',now(),now()),
      ('638',true,'Akala','Akala ',now(),now()),
      ('640',true,'J.P.Morgan Casa de Bolsa','J.P.Morgan Casa de Bolsa ',now(),now()),
      ('642',true,'Reforma','Operadora de Recursos Reforma',now(),now()),
      ('646',true,'STP','Sistema de Transferencias y Pagos STPSOFOM ENR',now(),now()),
      ('647',true,'Telecomm','Telecomunicaciones de México',now(),now()),
      ('648',true,'Evercore','Evercore Casa de Bolsa',now(),now()),
      ('649',true,'Skandia','Skandia Operadora de Fondos',now(),now()),
      ('651',true,'Seguros Monterrey New York Life','Seguros Monterrey New York Life',now(),now()),
      ('652',true,'ASEA','Solución Asea',now(),now()),
      ('653',true,'Kuspit','Kuspit Casa de Bolsa',now(),now()),
      ('655',true,'Sofiexpress','Sofiexpress',now(),now()),
      ('656',true,'Unagra','Unagra',now(),now()),
      ('659',true,'Opciones Empresariales del Noroeste','Opciones Empresariales del Noroeste',now(),now()),
      ('901',true,'Cls Bank International','Cls Bank International',now(),now()),
      ('902',true,'Indeval','Indeval',now(),now()),
      ('670',true,'Libertad','Libertad Servicios Financieros',now(),now()),
      ('999',true,'N/A','No Aplica',now(),now());
    "
  end

  def down do
    execute "DELETE FROM banks_catalog;"
  end
end
